import type { Metadata } from "next";
import "@/assets/styles/globals.css";



export const metadata: Metadata = {
  title: "Next template",
  keywords: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
