import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"
import Bootstrap from "./bootstrap";
import "@/assets/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Next template",
  keywords: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Bootstrap/>
      <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
